# Tên của workflow, sẽ hiển thị trong tab "Actions"
name: Deploy Portfolio to GitHub Pages

# 1. KÍCH HOẠT (TRIGGER)
on:
  # Chạy workflow này mỗi khi có push lên nhánh 'dev'
  push:
    branches:
      - dev
  # Cho phép bạn chạy workflow này thủ công từ tab Actions
  workflow_dispatch:

# 2. PHÂN QUYỀN (PERMISSIONS)
# Cấp quyền cho workflow để ghi vào môi trường của GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 3. CÁC CÔNG VIỆC (JOBS)
# Một workflow có thể có một hoặc nhiều jobs
jobs:
  # Đặt tên cho job là 'deploy'
  deploy:
    # Chạy job này trên một máy ảo Ubuntu phiên bản mới nhất
    runs-on: ubuntu-latest
    
    # Thiết lập môi trường triển khai là 'github-pages'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Các bước thực thi của job
    steps:
      # Bước 1: Lấy mã nguồn từ repository về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Đóng gói các file tĩnh để chuẩn bị deploy
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Bước 3: Đóng gói (tạo artifact) từ thư mục 'public' của bạn
      # Đây là bước quan trọng nhất cho trường hợp của bạn
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Chỉ định đường dẫn tới thư mục chứa file index.html và CSS
          path: './Portfolio/public'

      # Bước 4: Deploy artifact lên GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4